### ISSUE TITLE
/draai en /draaiweer moet één worden. net zoals braldt en leanne.

### ISSUE THREAD

**Issue by Maartenwut** [Maartenwut/DeCirkeltrekBot#4]
<3

**Comment by Flippylosaurus** [comment]
ik ook, bedankt

**Comment by Maartenwut** [comment]
<?php

$arr = Array('k', 't');
if (contains("kut", $arr)) {
        echo 'ja';
}else{
        echo'nee';                                                                                    }                                                                                                     
echo '<br><br>';

if (contains("hoi", $arr)) {
        echo 'ja';
}else{
        echo 'nee';
}

function contains($str, array $arr) {
    foreach($arr as $a) {
        if (stripos($str,$a) !== false) return true;
    }
    return false;
}


Doe er wat leuks mee

**Comment by Maartenwut** [comment]
Wel negeren voor o, u, b, d, p, q, s, z en x!

**Comment by Maartenwut** [comment]
neuk jullie ik heb het gedaan
