### ISSUE TITLE
maak status functie

### ISSUE THREAD

**Issue by Maartenwut** [Maartenwut/DeCirkeltrekBot#7]
{"ok":true,"result":[{"update_id":837184576,
"message":{"message_id":3,"from":{"id":12061586,"first_name":"Maarten","last_name":"Dekkers","username":"Maartenwut"},"chat":{"id":-175730377,"title":"Teeeest","type":"group"},"date":1473920678,"left_chat_participant":{"id":263767029,"first_name":"Hoi","username":"Maartentestbot"},"left_chat_member":{"id":263767029,"first_name":"Hoi","username":"Maartentestbot"}}},{"update_id":837184577,
"message":{"message_id":4,"from":{"id":12061586,"first_name":"Maarten","last_name":"Dekkers","username":"Maartenwut"},"chat":{"id":-175730377,"title":"Teeeest","type":"group"},"date":1473920685,"new_chat_participant":{"id":263767029,"first_name":"Hoi","username":"Maartentestbot"},"new_chat_member":{"id":263767029,"first_name":"Hoi","username":"Maartentestbot"}}},{"update_id":837184578,
"message":{"message_id":5,"from":{"id":12061586,"first_name":"Maarten","last_name":"Dekkers","username":"Maartenwut"},"chat":{"id":-175730377,"title":"...","type":"group"},"date":1473920710,"new_chat_title":"..."}},{"update_id":837184579,
"message":{"message_id":2,"from":{"id":12061586,"first_name":"Maarten","last_name":"Dekkers","username":"Maartenwut"},"chat":{"id":-1001084800952,"title":"Xx","type":"supergroup"},"date":1473920854,"new_chat_participant":{"id":263767029,"first_name":"Hoi","username":"Maartentestbot"},"new_chat_member":{"id":263767029,"first_name":"Hoi","username":"Maartentestbot"}}},{"update_id":837184580,
"message":{"message_id":3,"from":{"id":12061586,"first_name":"Maarten","last_name":"Dekkers","username":"Maartenwut"},"chat":{"id":-1001084800952,"title":"Xx","type":"supergroup"},"date":1473920858,"text":"Dd"}},{"update_id":837184581,
"message":{"message_id":4,"from":{"id":12061586,"first_name":"Maarten","last_name":"Dekkers","username":"Maartenwut"},"chat":{"id":-1001084800952,"title":"Xx","type":"supergroup"},"date":1473920862,"pinned_message":{"message_id":3,"from":{"id":12061586,"first_name":"Maarten","last_name":"Dekkers","username":"Maartenwut"},"chat":{"id":-1001084800952,"title":"Xx","type":"supergroup"},"date":1473920858,"text":"Dd"}}}]}

**Comment by notinecrafter** [comment]
Dafuq is dit?

**Comment by Maartenwut** [comment]
Wippen
